config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :merchant_aliases

  namespace :api do
    resources :docs, only: [:index]
  end

  get 'main_page/home'

  resources :stop_orders do
    resources :manage_account, controller: 'stop_orders/manage_account',  only: [:show, :update]
  end

  resources :charge_wizards

  resources :invite_requests, only: [:new, :create]

  resources :linked_accounts do
    collection do
      post :plaid_webhook
      post :unlink
    end
  end

  post '/pusher/auth' => 'pusher#auth'
  
  resources :financial_institutions, only: :index

  resources :account_details, only: [:new, :create, :edit, :update] do
    collection do
      get :turn_off_intro
      get :turn_on_intro
    end
  end

  resources :merchants

  resources :charges do
    resources :stop_orders, only: :new
    collection do
      post :create_then_manage
      get :search
      get :outlook
    end
  end

  resources :stop_orders, only: [:create, :show, :edit, :destroy, :index]
  resources :verifications, only: [:new, :create], defaults: {format: 'js'}
  resources :contact_preferences, only: :update, defaults: {format: 'js'}

  devise_for :users
  ActiveAdmin.routes(self)

  authenticated :user do
    devise_scope :user do
      root to: "charges#index", :as => "home"
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'landing', to: 'static_pages#landing'
  get 'legal', to: 'static_pages#legal'
  get 'about', to: 'static_pages#about'
  get 'test', to: 'static_pages#test'
  get 'privacy', to: 'static_pages#privacy'
  get 't', to: 'static_pages#t'
  get 'upgrades', to: 'static_pages#upgrades'

  root 'static_pages#landing'

end

app/views/shared/_charge_item.html.haml
.well.charge-item{class: "merchant-#{charge.descriptor.downcase.gsub(/\W/, '')}", id: "charge-item-#{charge.id.present? ? charge.id : 'new'}" }
  .charge-info-container
    -if (charge.amount.present? && charge.amount > 0) || (charge.renewal_period_in_weeks.present? && charge.renewal_period_in_weeks > 0) || charge.history.present?
      .charge-info.charge-amount.text-center{style: "padding-right: 10px;"}      
        -if charge.amount.present? && charge.amount > 0
          .charge-lead
            %p=number_to_currency(charge.amount_in_currency)
        
        -if charge.renewal_period_in_weeks.present? && charge.renewal_period_in_weeks > 0
          %p.without-margin
            =billing_interval_in_words(charge.renewal_period_in_weeks)
        -if charge.history.present?
          .small
            %a.icon-link{href: "#a", tabindex: "0", data: {toggle: "popover", content: formatted_history(charge.history_with_long_dates)} }
              %i.fa.fa-calendar
              history
              
    .charge-info.charge-description.text-left  
      .charge-lead
        %p=charge.descriptor

      %p.without-margin
        %span.gray
          -if charge.next_billing_date.present?
            %i.fa.fa-clock-o.hidden-md
            =time_to_next_bill(charge.next_billing_date)
          -elsif charge.billing_day.present?
            %i.fa.fa-clock-o.hidden-md
            ="last charge " + (distance_of_time_in_words charge.billing_day.to_time - Time.now) + " ago"
    
    .charge-info.charge-buttons.text-center      
      -if stop_order_charge_ids.include?(charge.id)
        =render partial: "stop_orders/show", locals: {stop_order: charge.active_stop_order}
      -else        
        .btn-group-vertical.text-center{role: "group", style: "width: 100%"}
          =link_to stop_orders_path(charge_id: charge.id, option: "cancel_all"), method: :post, class: "btn btn-charge", style: "border-top-right-radius: 3px;" do
            %i.fa.fa-stop
            cancel
          .btn-group
            %button.btn.btn-charge{style: "border-bottom-right-radius: 3px; border-top: 1px solid rgb(231, 231, 231);", data: {toggle: "dropdown"}} 
              modify
              %span.caret
            %ul.dropdown-menu.dropdown-menu-right
              %li              
                =link_to stop_orders_path(charge_id: charge.id, option: "upgrade"), method: :post do
                  %i.fa.fa-upgrade
                  upgrade
              %li
                =link_to stop_orders_path(charge_id: charge.id, option: "downgrade"), method: :post do
                  %i.fa.fa-downgrade
                  downgrade
              %li
                =link_to edit_charge_path(charge), remote: true do
                  %i.fa.fa-edit
                  edit expense info

app/views/shared/_financial_institutions.html.haml
.row#linked-account-index
  -FinancialInstitution.connect_enabled.in_groups_of(4, false) do |institution_group|   
    .col-md-6
      %ul.list-group.wizard-list-group
        -institution_group.each do |institution|  
          -linked_account = current_user.linked_account_at?(institution.id).presence || @linked_account
          %li.list-group-item{ data: { linked_account_id: linked_account.present? ? linked_account.id : nil } }
            .row
              .col-xs-6
                %span.lead=institution.name
              .col-xs-6.text-right
                -if linked_account.present? && linked_account.status != "started"
                    
                  -if linked_account.status == "linked"
                    
                    -if linked_account.error_message.blank?
                      =link_to linked_account, class: "btn btn-primary-o btn-responsive linked-account-button", data: {user_id: current_user.id} do
                        %i.fa.fa-link
                        View Expenses

                    -else
                      .tooltip-container{ data: {toggle: "tooltip", placement: "left", title: "Message from your account: #{linked_account.error_message}" }}
                        
                        =link_to new_linked_account_path(financial_institution_id: institution.id), remote: true, class: "btn btn-primary-o btn-responsive linked-account-button" do
                          Needs Attention

                  -elsif linked_account.status == "unlinked"
                    =link_to linked_account, class: "btn btn-warning btn-responsive linked-account-button" do 
                      Unlinked
                    =link_to "Re-Link", new_linked_account_path(financial_institution_id: institution.id), remote: true, class: "btn btn-primary btn-responsive linked-account-button"

                  -elsif linked_account.status == "mfa"
                    =link_to "Link", new_linked_account_path(financial_institution_id: institution.id), remote: true, class: "btn btn-primary btn-responsive"

                  -elsif linked_account.status == "delayed"
                    .tooltip-container{ data: {toggle: "tooltip", placement: "left", title: "#{linked_account.name} is taking longer than normal to respond.  Don't worry we'll send you an email when the process is complete." }}
                      %a.btn.btn-primary-o.btn-responsive.linked-account-button{disabled: "disabled"}
                        %i.fa.fa-clock-o
                        Delayed

                  -else
                    .tooltip-container{ data: {toggle: "tooltip", placement: "left", title: "Trym is #{linked_account.status} data from #{linked_account.account_name} to indentify potentially recurring charges.  This shouldn't take long." }}
                      %a.btn.btn-primary-o.btn-responsive.linked-account-button{disabled: "disabled"}
                        %i.fa.fa-circle-o-notch.fa-spin
                        =linked_account.status.titlecase

                -else
                  .tooltip-container
                    =link_to "Link", new_linked_account_path(financial_institution_id: institution.id), remote: true, class: "btn btn-primary btn-responsive"

app/views/shared/_security_and_terms.html.haml
%p.text-center
  =link_to "Security", about_path(anchor: "security")
  &bull;  
  =link_to "Privacy", privacy_path
  &bull;
  =link_to "Terms of Use", legal_path

app/views/shared/_security_notice.html.haml
Trym uses industry leading security to protect your data.  Click 
=link_to "here", about_path(anchor: "security") 
to learn about the measures we take to keep your information secure.