config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :merchant_aliases

  namespace :api do
    resources :docs, only: [:index]
  end

  get 'main_page/home'

  resources :stop_orders do
    resources :manage_account, controller: 'stop_orders/manage_account',  only: [:show, :update]
  end

  resources :charge_wizards

  resources :invite_requests, only: [:new, :create]

  resources :linked_accounts do
    collection do
      post :plaid_webhook
      post :unlink
    end
  end

  post '/pusher/auth' => 'pusher#auth'
  
  resources :financial_institutions, only: :index

  resources :account_details, only: [:new, :create, :edit, :update] do
    collection do
      get :turn_off_intro
      get :turn_on_intro
    end
  end

  resources :merchants

  resources :charges do
    resources :stop_orders, only: :new
    collection do
      post :create_then_manage
      get :search
      get :outlook
    end
  end

  resources :stop_orders, only: [:create, :show, :edit, :destroy, :index]
  resources :verifications, only: [:new, :create], defaults: {format: 'js'}
  resources :contact_preferences, only: :update, defaults: {format: 'js'}

  devise_for :users
  ActiveAdmin.routes(self)

  authenticated :user do
    devise_scope :user do
      root to: "charges#index", :as => "home"
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'landing', to: 'static_pages#landing'
  get 'legal', to: 'static_pages#legal'
  get 'about', to: 'static_pages#about'
  get 'test', to: 'static_pages#test'
  get 'privacy', to: 'static_pages#privacy'
  get 't', to: 'static_pages#t'
  get 'upgrades', to: 'static_pages#upgrades'

  root 'static_pages#landing'

end

app/models/financial_institution.rb
class FinancialInstitution < ActiveRecord::Base
end

app/controllers/api/v1/financial_institutions_controller.rb
class FinancialInstitutionsController < ApplicationController
  before_action :set_financial_institution, only: [:show, :edit, :update, :destroy]

  # GET /financial_institutions
  # GET /financial_institutions.json
  def index
    @financial_institutions = FinancialInstitution.all
  end

  # GET /financial_institutions/1
  # GET /financial_institutions/1.json
  def show
  end

  # GET /financial_institutions/new
  def new
    @financial_institution = FinancialInstitution.new
  end

  # GET /financial_institutions/1/edit
  def edit
  end

  # POST /financial_institutions
  # POST /financial_institutions.json
  def create
    @financial_institution = FinancialInstitution.new(financial_institution_params)

    respond_to do |format|
      if @financial_institution.save
        format.html { redirect_to @financial_institution, notice: 'Financial institution was successfully created.' }
        format.json { render :show, status: :created, location: @financial_institution }
      else
        format.html { render :new }
        format.json { render json: @financial_institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /financial_institutions/1
  # PATCH/PUT /financial_institutions/1.json
  def update
    respond_to do |format|
      if @financial_institution.update(financial_institution_params)
        format.html { redirect_to @financial_institution, notice: 'Financial institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @financial_institution }
      else
        format.html { render :edit }
        format.json { render json: @financial_institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /financial_institutions/1
  # DELETE /financial_institutions/1.json
  def destroy
    @financial_institution.destroy
    respond_to do |format|
      format.html { redirect_to financial_institutions_url, notice: 'Financial institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_financial_institution
      @financial_institution = FinancialInstitution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def financial_institution_params
      params.require(:financial_institution).permit(:name, :plaid_type, :has_mfa, :mfa, :plaid_id, :connect)
    end
end

app/helpers/financial_institutions_helper.rb
module FinancialInstitutionsHelper
end

app/views/financial_institutions/_form.html.erb
<%= form_for(@financial_institution) do |f| %>
  <% if @financial_institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@financial_institution.errors.count, "error") %> prohibited this financial_institution from being saved:</h2>

      <ul>
      <% @financial_institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :plaid_type %><br>
    <%= f.text_field :plaid_type %>
  </div>
  <div class="field">
    <%= f.label :has_mfa %><br>
    <%= f.check_box :has_mfa %>
  </div>
  <div class="field">
    <%= f.label :mfa %><br>
    <%= f.text_field :mfa %>
  </div>
  <div class="field">
    <%= f.label :plaid_id %><br>
    <%= f.text_field :plaid_id %>
  </div>
  <div class="field">
    <%= f.label :connect %><br>
    <%= f.check_box :connect %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/financial_institutions/edit.html.erb
<h1>Editing Financial Institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @financial_institution %> |
<%= link_to 'Back', financial_institutions_path %>

app/views/financial_institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Financial Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Plaid type</th>
      <th>Has mfa</th>
      <th>Mfa</th>
      <th>Plaid</th>
      <th>Connect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @financial_institutions.each do |financial_institution| %>
      <tr>
        <td><%= financial_institution.name %></td>
        <td><%= financial_institution.plaid_type %></td>
        <td><%= financial_institution.has_mfa %></td>
        <td><%= financial_institution.mfa %></td>
        <td><%= financial_institution.plaid_id %></td>
        <td><%= financial_institution.connect %></td>
        <td><%= link_to 'Show', financial_institution %></td>
        <td><%= link_to 'Edit', edit_financial_institution_path(financial_institution) %></td>
        <td><%= link_to 'Destroy', financial_institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Financial institution', new_financial_institution_path %>

app/views/financial_institutions/new.html.erb
<h1>New Financial Institution</h1>

<%= render 'form' %>

<%= link_to 'Back', financial_institutions_path %>

app/views/financial_institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @financial_institution.name %>
</p>

<p>
  <strong>Plaid type:</strong>
  <%= @financial_institution.plaid_type %>
</p>

<p>
  <strong>Has mfa:</strong>
  <%= @financial_institution.has_mfa %>
</p>

<p>
  <strong>Mfa:</strong>
  <%= @financial_institution.mfa %>
</p>

<p>
  <strong>Plaid:</strong>
  <%= @financial_institution.plaid_id %>
</p>

<p>
  <strong>Connect:</strong>
  <%= @financial_institution.connect %>
</p>

<%= link_to 'Edit', edit_financial_institution_path(@financial_institution) %> |
<%= link_to 'Back', financial_institutions_path %>