config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :merchant_aliases

  namespace :api do
    resources :docs, only: [:index]
  end

  get 'main_page/home'

  resources :stop_orders do
    resources :manage_account, controller: 'stop_orders/manage_account',  only: [:show, :update]
  end

  resources :charge_wizards

  resources :invite_requests, only: [:new, :create]

  resources :linked_accounts do
    collection do
      post :plaid_webhook
      post :unlink
    end
  end

  post '/pusher/auth' => 'pusher#auth'
  
  resources :financial_institutions, only: :index

  resources :account_details, only: [:new, :create, :edit, :update] do
    collection do
      get :turn_off_intro
      get :turn_on_intro
    end
  end

  resources :merchants

  resources :charges do
    resources :stop_orders, only: :new
    collection do
      post :create_then_manage
      get :search
      get :outlook
    end
  end

  resources :stop_orders, only: [:create, :show, :edit, :destroy, :index]
  resources :verifications, only: [:new, :create], defaults: {format: 'js'}
  resources :contact_preferences, only: :update, defaults: {format: 'js'}

  devise_for :users
  ActiveAdmin.routes(self)

  authenticated :user do
    devise_scope :user do
      root to: "charges#index", :as => "home"
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'landing', to: 'static_pages#landing'
  get 'legal', to: 'static_pages#legal'
  get 'about', to: 'static_pages#about'
  get 'test', to: 'static_pages#test'
  get 'privacy', to: 'static_pages#privacy'
  get 't', to: 'static_pages#t'
  get 'upgrades', to: 'static_pages#upgrades'

  root 'static_pages#landing'

end

app/models/linked_account.rb
class LinkedAccount < ActiveRecord::Base
  belongs_to :user
  belongs_to :financial_institution
  validates_uniqueness_of :user_id, scope: [:financial_institution_id, :destroyed_at], if: Proc.new { |link| link.destroyed_at.nil? }
  validates :status, inclusion: { in: %w(started mfa syncing analyzing linked unlinked delayed) }

  has_many :charges
  has_many :transaction_requests
  has_many :transactions, through: :transaction_requests

  scope :linked, -> {where( status: ["syncing", "analyzing", "linked"] )}
  scope :not_destroyed, -> {where( destroyed_at: nil)}
  default_scope {not_destroyed}

  def error_message
    return nil if (last_api_response.nil? || last_api_response["response_code"].to_i < 202)
    PlaidErrorHandler.new(last_api_response).message_for_user
  end

  def mfa_prompt
    return nil unless (mfa_question.present? && mfa_type.present?)
    if mfa_type == "question"
      mfa_question
    else
      delivered_to = mfa_question.split(' ').last
      delivery_method = delivered_to.include?("@") ? "email" : "phone"
      "Please enter the security code which #{account_name} sent to your #{delivered_to} #{delivery_method}"
    end
  end

  def plaid_webhook_handler(params)
    case params["code"].to_i
    when 0
      true
    when 1..2
      button_icon = "circle-o-notch fa-spin"
      button_text = "analyzing"
      button_tooltip = "Trym is searching through your transactions from #{account_name} to indentify potentially recurring charges.  This should only take a few seconds."
      button_link = '#'
      flash = ''
      button_disabled_state = "disabled"
      PlaidTransactionGetter.perform_async(id)
      push_update_to_client({
        button_icon: button_icon, 
        button_text: button_text, 
        button_tooltip: button_tooltip, 
        button_link: button_link, 
        button_disabled_state: button_disabled_state,
        flash: flash
      })
    when 3..4
      true
    when 1205
      button_icon = "warning"
      button_text = "locked"
      button_tooltip = "Please log into #{account_name}'s website to unlock your account.  Once you've done that click here to relink your account"
      button_link = Rails.application.routes.url_helpers.new_linked_account_path
      button_disabled_state = "false"
      flash = "It appears your account is locked.  Please visit #{account_name}'s website to unlock it."
      push_update_to_client({
        button_icon: button_icon, 
        button_text: button_text, 
        button_tooltip: button_tooltip, 
        button_link: button_link, 
        button_disabled_state: button_disabled_state, 
        flash: flash
      })    
    else
      Rails.logger.error "Trym Webhook Unhandled Response for linked_account=#{id}.  Response Body: #{params.inspect}"
    end
  end

  def delink
    AccountDelinker.perform_async(id)
    update!( destroyed_at: Time.now )
    if charges.present?
      charges.recurring.update_all(linked_account_id: nil)
      charges.delete_all
    end
    true
  end

  def account_name
    financial_institution.name
  end

  def name
    financial_institution.name
  end


  #stub functions for forms
  def username
  end

  def password
  end

  def pin
  end

  def push_update_to_client(message)
    channel_name = 'private-user-' + user.id.to_s + '-channel'
    Pusher[channel_name].trigger( "linked-account-notifications", {
      linked_account_id: id,
      linked_account_name: account_name,
      message: message
    })
  end

end

app/controllers/api/v1/linked_accounts_controller.rb
class LinkedAccountsController < ApplicationController
  before_action :set_linked_account, only: [:show, :edit, :update, :destroy]

  # GET /linked_accounts
  # GET /linked_accounts.json
  def index
    @linked_accounts = LinkedAccount.all
  end

  # GET /linked_accounts/1
  # GET /linked_accounts/1.json
  def show
  end

  # GET /linked_accounts/new
  def new
    @linked_account = LinkedAccount.new
  end

  # GET /linked_accounts/1/edit
  def edit
  end

  # POST /linked_accounts
  # POST /linked_accounts.json
  def create
    @linked_account = LinkedAccount.new(linked_account_params)

    respond_to do |format|
      if @linked_account.save
        format.html { redirect_to @linked_account, notice: 'Linked account was successfully created.' }
        format.json { render :show, status: :created, location: @linked_account }
      else
        format.html { render :new }
        format.json { render json: @linked_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linked_accounts/1
  # PATCH/PUT /linked_accounts/1.json
  def update
    respond_to do |format|
      if @linked_account.update(linked_account_params)
        format.html { redirect_to @linked_account, notice: 'Linked account was successfully updated.' }
        format.json { render :show, status: :ok, location: @linked_account }
      else
        format.html { render :edit }
        format.json { render json: @linked_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linked_accounts/1
  # DELETE /linked_accounts/1.json
  def destroy
    @linked_account.destroy
    respond_to do |format|
      format.html { redirect_to linked_accounts_url, notice: 'Linked account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linked_account
      @linked_account = LinkedAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linked_account_params
      params.require(:linked_account).permit(:user_id, :financial_institution_id, :plaid_access_token, :last_successful_sync, :last_api_response, :mfa_question, :mfa_type, :destroyed_at, :status)
    end
end

app/controllers/linked_accounts_controller.rb
class LinkedAccountsController < ApplicationController
  before_action :authenticate_user!, except: :plaid_webhook
  before_action :set_linked_account, only: [:show, :edit, :update, :destroy, :unlink]

  skip_before_filter :verify_authenticity_token, only: :plaid_webhook

  respond_to :html, :js, :json

  def show
    unless request_format == :json
      @charges = @linked_account.charges.sort_by_recurring_score.page(params[:page])
    end

    respond_with(@linked_account)
  end

  def index
    @linked_accounts = current_user.linked_accounts
  end

  def new
    @financial_institution = FinancialInstitution.find(params[:financial_institution_id]) if params[:financial_institution_id].present?
    @linked_account = LinkedAccount.new
    respond_with(@linked_account)
  end

  def create
    @linked_account = LinkedAccount.find_or_create_by(linked_account_params)
    if @linked_account.errors.present?
      render 'error'
    else
      @linked_account.update( last_api_response: nil )
      
      AccountLinker.perform_async( account_linker_params, @linked_account.id )
    end
  end

  def unlink
    if @linked_account.present?
      @linked_account.update( status: "unlinked" )
      PlaidAccountDelinker.perform_async( @linked_account.id )
    else
      flash[:error] = "Whoops.  Something went wrong."
    end
    redirect_to :back
  end

  def plaid_webhook
    if params["access_token"]
      @linked_account = LinkedAccount.find_by_plaid_access_token( params["access_token"] )
    end

    if @linked_account.present? && @linked_account.status != "unlinked"
      @linked_account.plaid_webhook_handler(params)
    else
      Rails.logger.error "Trym Webhook For Orphaned Account!! Response Body: #{params.inspect}"
    end

    head :ok, content_type: "text/html"
  end

  def edit
  end

  def update
    #TODO: Handle Reauth / Account Destroy
    if ["201","402"].include? @linked_account.last_api_response["response_code"]
      @linked_account.update( last_api_response: nil )
      
      AccountLinker.perform_async( mfa_params, @linked_account.id )
    end
  end

  def destroy
    @linked_account.delink
    redirect_to root_path
  end

  private
    def set_linked_account
      @linked_account = current_user.linked_accounts.find(params[:id])
    end

    def linked_account_params
      params.require(:linked_account).permit(:financial_institution_id).merge({ user_id: current_user.id })
    end

    def account_linker_params
      params.require(:linked_account).permit(:username, :password, :pin)
    end

    def mfa_params
      params.require(:linked_account).permit(:mfa_response)
    end

end

app/helpers/linked_accounts_helper.rb
module LinkedAccountsHelper
end

app/views/linked_accounts/_form.html.erb
<%= form_for(@linked_account) do |f| %>
  <% if @linked_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linked_account.errors.count, "error") %> prohibited this linked_account from being saved:</h2>

      <ul>
      <% @linked_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :financial_institution_id %><br>
    <%= f.text_field :financial_institution_id %>
  </div>
  <div class="field">
    <%= f.label :plaid_access_token %><br>
    <%= f.text_field :plaid_access_token %>
  </div>
  <div class="field">
    <%= f.label :last_successful_sync %><br>
    <%= f.datetime_select :last_successful_sync %>
  </div>
  <div class="field">
    <%= f.label :last_api_response %><br>
    <%= f.text_field :last_api_response %>
  </div>
  <div class="field">
    <%= f.label :mfa_question %><br>
    <%= f.text_area :mfa_question %>
  </div>
  <div class="field">
    <%= f.label :mfa_type %><br>
    <%= f.text_area :mfa_type %>
  </div>
  <div class="field">
    <%= f.label :destroyed_at %><br>
    <%= f.datetime_select :destroyed_at %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_area :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/linked_accounts/edit.html.erb
<h1>Editing Linked Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @linked_account %> |
<%= link_to 'Back', linked_accounts_path %>

app/views/linked_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Linked Accounts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Financial institution</th>
      <th>Plaid access token</th>
      <th>Last successful sync</th>
      <th>Last api response</th>
      <th>Mfa question</th>
      <th>Mfa type</th>
      <th>Destroyed at</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linked_accounts.each do |linked_account| %>
      <tr>
        <td><%= linked_account.user %></td>
        <td><%= linked_account.financial_institution %></td>
        <td><%= linked_account.plaid_access_token %></td>
        <td><%= linked_account.last_successful_sync %></td>
        <td><%= linked_account.last_api_response %></td>
        <td><%= linked_account.mfa_question %></td>
        <td><%= linked_account.mfa_type %></td>
        <td><%= linked_account.destroyed_at %></td>
        <td><%= linked_account.status %></td>
        <td><%= link_to 'Show', linked_account %></td>
        <td><%= link_to 'Edit', edit_linked_account_path(linked_account) %></td>
        <td><%= link_to 'Destroy', linked_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linked account', new_linked_account_path %>

app/views/linked_accounts/index.html.haml
.row
  .col-md-10.col-md-offset-1
    .paragraph-spacer
    .text-center
      .trym-talking
        %p.lead.without-margin
          Link your accounts and I will help you find recurring expenses automatically.

    .paragraph-spacer

    %p.lead.text-center
      =link_to search_charges_path, class: "btn btn-primary-o" do 
        %i.fa.fa-list
        View transactions across your linked accounts
    =render 'shared/financial_institutions'

.row
  .col-lg-8.col-lg-offset-2
    .well
      %p.strong.text-center
        Here's how account linking works
      %ul
        %li
          =render 'shared/security_notice'
        %li Trym scans linked accounts every day and alerts you if it find new expenses which look recurring.
        %li You can unlink an account at any time by clicking on the "unlink" button on any linked account's page.
        %li If you unlink an account Trym will delete its connection to your account and will stop scanning it for recurring expenses.
        %li If your account is being updated, it will show as "syncing" or "analyzing" until the update is complete.
        %li 
          Questions? 
          %a{href: "mailto: team@trym.io"} Just ask.

=render 'shared/security_and_terms'
  

app/views/linked_accounts/new.html.erb
<h1>New Linked Account</h1>

<%= render 'form' %>

<%= link_to 'Back', linked_accounts_path %>

app/views/linked_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @linked_account.user %>
</p>

<p>
  <strong>Financial institution:</strong>
  <%= @linked_account.financial_institution %>
</p>

<p>
  <strong>Plaid access token:</strong>
  <%= @linked_account.plaid_access_token %>
</p>

<p>
  <strong>Last successful sync:</strong>
  <%= @linked_account.last_successful_sync %>
</p>

<p>
  <strong>Last api response:</strong>
  <%= @linked_account.last_api_response %>
</p>

<p>
  <strong>Mfa question:</strong>
  <%= @linked_account.mfa_question %>
</p>

<p>
  <strong>Mfa type:</strong>
  <%= @linked_account.mfa_type %>
</p>

<p>
  <strong>Destroyed at:</strong>
  <%= @linked_account.destroyed_at %>
</p>

<p>
  <strong>Status:</strong>
  <%= @linked_account.status %>
</p>

<%= link_to 'Edit', edit_linked_account_path(@linked_account) %> |
<%= link_to 'Back', linked_accounts_path %>

app/views/linked_accounts/show.html.haml
-if @linked_account.error_message
  #flash-container
    .alert{role: 'alert', class: flash_alert_type("alert") }
      %p.without-margin.lead.text-center
        %i.fa.fa-exclamation-circle{ style: "color: #f0ad4e;"}
        %span= @linked_account.error_message

-else 
  .container#scrollable-with-offset
    .row      
      .col-xs-12.scrollable        
        -if @linked_account.status == "unlinked"
          %h2
            =@linked_account.financial_institution.name
          .unlinked-info-box
            %h3
              %i.fa.fa-unlink{style: "color: #f0ad4e"}
              Account Unlinked
              =link_to new_linked_account_path(financial_institution_id: @linked_account.financial_institution_id), remote: true, class: "btn btn-primary btn-xs" do
                %i.fa.fa-link
                relink 
                %span.hidden-xs this account
            %p This account has been unlinked. Trym will no longer automatically search your account for new transactions or update you on changes to recurring expenses from this account.  You may relink this account at any time by re-entering your linked account credentials.

        -else
          %h2
            =@linked_account.financial_institution.name
            %br.visible-xs-block
            =link_to unlink_linked_accounts_path(id: @linked_account.id), method: :post, class: "btn btn-danger btn-sm linked-account-charges-buttons", data: {confirm: "Are you sure you want to unlink this account? To relink it you will need to re-enter your account credentials."} do
              %i.fa.fa-unlink{style: "color: white"}
              unlink account

        -if @linked_account.status == "delayed"
          .unlinked-info-box
            %h3 
              %i.fa.fa-clock-o{style: "color: #f0ad4e"}
              Linking Delayed

            %p.lead
              It's taking longer than normal to sync your #{@linked_account.name} account. We'll send you an email when it's finished. Please email us at
              =link_to "support@trym.io", "mailto:support@trym.io?subject=Issues with Linked Account ID:#{@linked_account.id}"
              if your account is not synced in the next 24 hours.


        -if @linked_account.charges.present?
          %p.lead  
            Transactions on this account for up to the past two years are displayed below. 
            %strong Trym puts expenses which look recurring at the top of the list.
            Tell Trym to monitor or manage any expense by checking "recurring" next to it. Based on your transaction history, Trym will notify you when you are likely to be re-charged for any recurring expense. 
        
          =render 'charges/table/table'

        -elsif @linked_account.status != "delayed"
          .unlinked-info-box
            %h3
              %i.fa.fa-warning{style: "color: #f0ad4e"}
              No transactions found

            %p.lead
              We have not found any transactions in this account yet.  If you can see transactions on your financial institution's website or think there should be transactions on this account please email us at
              =link_to "support@trym.io", "mailto:support@trym.io?subject=Issues with Linked Account ID:#{@linked_account.id}"
          .paragraph-spacer
          .paragraph-spacer
          .paragraph-spacer
          .paragraph-spacer
          .paragraph-spacer
          .paragraph-spacer
          .paragraph-spacer