config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :merchant_aliases

  namespace :api do
    resources :docs, only: [:index]
  end

  get 'main_page/home'

  resources :stop_orders do
    resources :manage_account, controller: 'stop_orders/manage_account',  only: [:show, :update]
  end

  resources :charge_wizards

  resources :invite_requests, only: [:new, :create]

  resources :linked_accounts do
    collection do
      post :plaid_webhook
      post :unlink
    end
  end

  post '/pusher/auth' => 'pusher#auth'
  
  resources :financial_institutions, only: :index

  resources :account_details, only: [:new, :create, :edit, :update] do
    collection do
      get :turn_off_intro
      get :turn_on_intro
    end
  end

  resources :merchants

  resources :charges do
    resources :stop_orders, only: :new
    collection do
      post :create_then_manage
      get :search
      get :outlook
    end
  end

  resources :stop_orders, only: [:create, :show, :edit, :destroy, :index]
  resources :verifications, only: [:new, :create], defaults: {format: 'js'}
  resources :contact_preferences, only: :update, defaults: {format: 'js'}

  devise_for :users
  ActiveAdmin.routes(self)

  authenticated :user do
    devise_scope :user do
      root to: "charges#index", :as => "home"
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'landing', to: 'static_pages#landing'
  get 'legal', to: 'static_pages#legal'
  get 'about', to: 'static_pages#about'
  get 'test', to: 'static_pages#test'
  get 'privacy', to: 'static_pages#privacy'
  get 't', to: 'static_pages#t'
  get 'upgrades', to: 'static_pages#upgrades'

  root 'static_pages#landing'

end

app/controllers/api/v1/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:description, :user_id, :amount, :start_date, :end_date, :renewal_period_in_weeks, :billing_day, :wizard_complete, :last_date_billed, :merchant_id, :recurring, :billed_to_date, :recurring_score, :transaction_request_id, :linked_account_id, :trym_category_id, :history, :plaid_name)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:edit, :update, :destroy]
  before_action :create_merchant_if_new, only: [:create, :create_then_manage, :update]
  before_action :convert_amount_to_number, only: [:create, :update]
  before_action :authenticate_user!

  respond_to :html, :js

  def index
    session.delete(:charge_wizard_categories)
    
    @charges = current_user.charges.recurring.page(params[:page]).per(15)
    @charges_outlook_chart_data = ChargesOutlookChartData.new(current_user, @charges)
    @linked_accounts = current_user.linked_accounts.linked
    @stop_orders = current_user.stop_orders.active_or_complete.order(created_at: :desc)
    
    respond_with(@charges)
  end

  def outlook    
    @charges_outlook_chart_data = ChargesOutlookChartData.new(current_user, current_user.charges.recurring.with_merchant)
  end

  def search
    @query = params[:q]
  
    if @query.present?
  
      merchant_ids = Merchant.where("name ILIKE ?", "%#{@query}%").pluck(:id)
      merchant_name_query = merchant_ids.present? ? " OR merchant_id IN (#{merchant_ids.join(',')})" : ''
      
      if params[:linked_account_id].present?
        @linked_account = LinkedAccount.find(params[:linked_account_id])
        @charges = @linked_account.charges.where("plaid_name ILIKE ? OR description ILIKE ?#{merchant_name_query}", "%#{@query}%", "%#{@query}%").
                                           sort_by_recurring_score.
                                           page(params[:page]).per(15)
      else
        @charges = current_user.charges.where("plaid_name ILIKE ? OR description ILIKE ?#{merchant_name_query}", "%#{@query}%", "%#{@query}%").
                                        sort_by_recurring_score.
                                        page(params[:page]).per(15)
      end

    else
      if params[:linked_account_id].present?
        @charges = @linked_account.charges.sort_by_recurring_score.page(params[:page]).per(15)
   
      else
        @charges = current_user.charges.from_link.sort_by_recurring_score.page(params[:page]).per(15)
      end
    end
  end

  def create_then_manage
    @charge = current_user.charges.find_or_create_by(charge_params)
    unless @charge.new_record?
      @stop_order = StopOrder.find_or_create_by( charge_id: @charge.id, status: "started" )
      redirect_to stop_order_manage_account_path( :manage_account, stop_order_id: @stop_order.id)
    end
  end

  def new
    @title = "new charge"
    @trym_category_id = TrymCategory.find(params[:trym_category_id]).id if params[:trym_category_id].present?

    @charge = current_user.charges.build( renewal_period_in_weeks: 4, trym_category_id: params[:trym_category_id])
  end

  def edit
    @attribute = params[:attribute]
  end

  def create
    @charge = current_user.charges.create(charge_params)
    respond_to do |format|
      format.js
      format.html {redirect_to charges_path}
    end
  end

  def update
    @charge.update(charge_params)
    respond_with(@charge)
  end

  def destroy
    @charge.destroy
  end

  private

    def set_charge
      @charge = current_user.charges.find(params[:id])
    end

    def charge_params
      params.require(:charge).permit(:merchant_id, :description, :amount, :recurring, :billing_day, :renewal_period_in_weeks, :trym_category_id)
    end

    def convert_amount_to_number
      unless (@charge.present? && @charge.amount.present? && params[:charge][:amount] == ( @charge.amount * 100 ))
        if params[:charge][:amount].is_a?(String)
          params[:charge][:amount] = (params[:charge][:amount].gsub("$","").gsub(" ","").to_f * 100).to_i
        end
      end
    end

    def create_merchant_if_new
      unless (@charge.present? && params[:charge][:merchant_id] == @charge.merchant_id) || params[:charge][:merchant_id].nil?
        if (true if Integer(params[:charge][:merchant_id]) rescue false)
          params[:charge][:merchant_id] = Merchant.find(params[:charge][:merchant_id]).id
        else
          params[:charge][:merchant_id] = Merchant.create(name: params[:charge][:merchant_id]).id
        end
      end
    end

end

app/helpers/charges_helper.rb
module ChargesHelper

  def recurring_factors_for(charge)
    return "<a data-toggle='tooltip' data-title='Trym thinks this expense is recurring because you created it'><i class='fa recurring-factor fa-user recurring-factor-good'></i></a>".html_safe unless charge.transactions.present?
    interval_class = "fa-calendar"
    amount_class = "fa-usd"
    category_class = "fa-tags"
    merchant_class = "fa-building"

    factors = TransactionScorer.new(charge.transactions).reason_for_score.collect do |r, v|
      {
        dates_are_perfectly_recurring: [interval_class, v],
        amounts_are_similar: [amount_class, v],
        amounts_are_not_similar: [amount_class, v],
        interval_likely_recurring: [interval_class, v],
        interval_looks_recurring_with_limited_data: [interval_class, v],
        interval_not_likely_recurring: [interval_class, v],
        last_charge_too_long_ago: [interval_class, v],
        one_transaction: [interval_class, v],
        one_transaction_more_than_one_month_ago: [interval_class, v],
        one_transaction_more_than_one_year_ago: [interval_class, v],
        likely_category: [category_class, v],
        very_likely_category: [category_class, v],
        unlikely_category: [category_class, v],
        very_unlikely_category: [category_class, v],
        likely_description: [category_class, v],
        unlikely_description: [category_class, v],
        merchant_recurring_score: [merchant_class, v]
      }[r]
    end.sort_by{ |_,v| v }.inject({}){ |h,(k,v)| h[k].present? ? h[k] += v : h[k] = v ; h}.reject{ |_,v| v.between?(-1,1) }.
        collect do |f, v| 
          recurring_explanation = "This expense appears #{ v > 0 ? '' : 'not' } to be recurring because " + {
            "fa-calendar" => "of when you were charged",
            "fa-usd" => "some past expenses were #{v < 0 ? 'not' : nil} for similar amounts",
            "fa-tags" => "of the merchant category provided by your bank",
            "fa-building" => "it recognized the merchant name"
          }[f]
          "<a data-toggle='tooltip' data-title='#{recurring_explanation}'>" + 
          "<i class='fa recurring-factor #{f} recurring-factor-#{v > 0 ? "good" : "bad"}'></i></a>"
        end.
        join(" ").html_safe

    factors.present? ? factors : "<small>n/a</small>".html_safe
  end

  def stop_order_charge_ids
    current_user.charges.with_active_stop_orders.pluck(:id)
  end

  def merchant_name_example_helper(trym_category_id)
    if trym_category_id.present?
      merchant_names = TrymCategory.find(trym_category_id).merchants.limit(2).pluck(:name)
      merchant_names.present? ? merchant_names.join(', ') + ', etc.' : "search for company"
    else
      "Cable/Internet, Cell Phone, Insurance, etc."
    end
  end

  def time_to_next_bill(next_billing_date)
    if next_billing_date == Date.today
      "due today"
    else
      "next charge in " +  (distance_of_time_in_words next_billing_date.to_time - Time.now.beginning_of_day)
    end
  end

  def billing_interval_in_words(renewal_period_in_weeks)
    interval = Charge.renewal_period_in_words[renewal_period_in_weeks]
    interval.present? ? interval.split(" - ").first : "#{renewal_period_in_weeks}-Weekly"
  end

  def charge_attribute_edit_link(charge, attribute, &block)
    link_to edit_charge_path(id: charge.id, attribute: attribute), class: "charge-mini-edit-link", remote: true, data:{placement: tooltip_placement_for(attribute)}, &block
  end

  def tooltip_placement_for(attribute)
    ["amount", "renewal_period_in_weeks"].include?(attribute) ? "left" : "right"
  end

  def attribute_input_value(charge, attribute)
    case attribute
    when "merchant" then nil
    when "amount" then number_to_currency(charge.amount / 100.0, precision: 2)
    when "billing_day" then charge.next_billing_date.present? ? charge.next_billing_date : charge.billing_day
    else 
      charge.send(attribute)
    end
  end

  def formatted_history(history)
    if history.present?
      "<div class='charge-history-container'>" +
      "<div class='strong charge-history-left'>2 Yr Total:</div><div class='strong charge-history-right'>#{number_to_currency history.values.inject(0.0){ |s,v| s+= v }}</div>" +
      history.to_a.reverse.collect{ |d,v| "<div><div class='charge-history-left'>#{d}:</div><div class='charge-history-right'>#{number_to_currency v}</div>" }.join("</div>")+
      "</div>"
    else
      nil
    end
  end

end

app/views/charges/_account_activity.html.haml
.heading
  %h5
    %i.fa.fa-history
    Expense Activity
    .pull-right.visible-lg-inline-block
      =link_to new_charge_path, class: "btn btn-xs btn-default", remote: true do
        %i.fa.fa-plus-circle
        Track New Expense
        
=link_to new_charge_path, class: "btn btn-xs btn-block sub-heading-link hidden-lg", remote: true do
  %i.fa.fa-plus-circle
  Track New Expense
.body
  -if @stop_orders.present?
    -@stop_orders.each do |s|
      .item.row
        .col-lg-5.col-sm-7.item-label{style: "padding-right:0px"}
          %span
            =s.charge.descriptor
            %br
            %small
              =link_to s.type_of_request, stop_order_path(s)
        .col-lg-7.col-sm-5.text-center
          .progress
            .progress-bar{ style: "width: #{s.progress_perc}", class: "progress-bar-#{s.progress_class}" }
          -if s.status == "succeeded"
            %i.fa.fa-circle-check
          %small=s.status
    .item-row
      .col-sm-12
        %h5
          Manage Another Expense
        %p.small
          Select a service provider below to cancel, upgrade, or downgrade your account with just a few clicks

        =form_for current_user.charges.build, url: create_then_manage_charges_path do |f|
          %p=f.text_field :merchant_id, data: { url: merchants_path, placeholder: "Click to select a service provider" }
          %p.text-center
            %button.btn.btn-default#disabled-next-button{disabled: "disabled"}
              Select a service to continue
            =f.button class: "btn btn-primary", id: "enabled-next-button" do 
              continue
              %i.fa.fa-arrow-circle-right

  -else
    .item.row
      .col-sm-12
        %h5
          No Expense History
        %p.small
          Select a service provider below to cancel, upgrade, or downgrade your account with just a few clicks

        =form_for current_user.charges.build, url: create_then_manage_charges_path do |f|
          %p=f.text_field :merchant_id, data: { url: merchants_path, placeholder: "Click to select a service provider" }
          %p.text-center
            %button.btn.btn-default#disabled-next-button{disabled: "disabled"}
              Select a service to continue
            =f.button class: "btn btn-primary", id: "enabled-next-button" do 
              continue
              %i.fa.fa-arrow-circle-right

app/views/charges/_contact.html.haml
.heading
  %h5
    %i.fa.fa-envelope-o
    Contact Preferences
.body
  .item.row
    .col-sm-12
      %h5 Send Email:
    .col-sm-12.prefs
      %span 3 Days Before Charge
      .pull-right
        %input.bootstrap-switch{type: "checkbox", checked: current_user.email_alert, data: {size: "mini", on_text: "Yes", off_text: "No", url: contact_preference_path(current_user.id, email_alert: "placeholder") }}
    .col-sm-12.prefs
      %span Monthly Summary
      .pull-right
        %input.bootstrap-switch{type: "checkbox", checked: current_user.email_summary, data: {size: "mini", on_text: "Yes", off_text: "No", url: contact_preference_path(current_user.id, email_summary: "placeholder") }}
  .item.row
    .col-sm-12
      %h5 Send Text Message:
    -if current_user.phone_verified?
      .col-sm-12.prefs
        %span 3 Days Before Charge
        .pull-right
          %input.bootstrap-switch{type: "checkbox", checked: current_user.text_alert, data: {size: "mini", on_text: "Yes", off_text: "No", url: contact_preference_path(current_user.id, text_alert: "placeholder") }}
      .col-sm-12.prefs
        %span Monthly Summary
        .pull-right
          %input.bootstrap-switch{type: "checkbox", checked: current_user.text_summary, data: {size: "mini", on_text: "Yes", off_text: "No", url: contact_preference_path(current_user.id, text_summary: "placeholder") }}
    -else
      .col-sm-12
        %p.text-center
          =link_to edit_user_registration_path do
            Add a phone number to enable text alerts

app/views/charges/_content.html.haml
.paragraph-spacer
.row.trym-fade-in
  .col-sm-12.text-center
    .trym-talking
      %p.lead.without-margin
        Hello#{current_user.first_name.present? ? ' ' + current_user.first_name : ''}, here's what i'm tracking for you.
    -if @charges_outlook_chart_data
      %p.lead
        You're on track to spend 
        %b #{number_to_currency @charges_outlook_chart_data.total_next_twelve_months}
        on recurring expenses over the next year.
    -else
      %p.lead
        Tell me more about any recurring expense by clicking modify > edit expense info.

.trym-fade-in
  .row#charge-list
    -(@charges.select(&:next_billing_date).sort_by(&:next_billing_date) + @charges.reject(&:next_billing_date)).in_groups_of(2,false) do |charge_group|
      -charge_group.each do |charge|
        %div{ class: "col-md-6 #{charge_group.size == 2 ? '' : 'col-md-offset-3'}" }
          =render partial: "shared/charge_item", locals: {charge: charge}

  .paragraph-spacer

  .row
    .col-md-4
      %p
        =link_to current_user.has_linked_charges? ? search_charges_path : linked_accounts_path, class: "btn btn-block btn-primary-o btn-icon-left" do
          %span
            %i.fa.fa-credit-card.fa-3x.pull-left
          %span Add expenses from linked accounts
    .col-md-4
      %p
        =link_to new_charge_path, class: "btn btn-block btn-primary-o btn-icon-left" do
          %span
            %i.fa.fa-plus-circle.fa-3x.pull-left
          %span Add new recurring expenses manually
    .col-md-4
      %p
        =link_to new_stop_order_path, class: "btn btn-block btn-primary-o btn-icon-left" do
          %span
            %i.fa.fa-cogs.fa-3x.pull-left
          %span Cancel or modify recurring expenses

  .paragraph-spacer

app/views/charges/_edit.html.haml
.modal-dialog.modal-sm
  .modal-content
    = simple_form_for @charge, remote: request.format.js? do |f|      
      = f.input :update_from, as: :hidden, input_html: {value: trym_referrer}
      .modal-body.text-center
        %h3.modal-title 
          %i.fa.fa-edit
          edit charge
        %p.form-errors
          = f.error_notification
        .form-inputs
          -if @trym_category_id.present?
            = f.input :trym_category_id, as: :hidden, input_html: {value: @trym_category_id}
          = f.input :merchant_id, as: :string, label: "Which company is the charge from?", input_html: {class: "text-center", data: {placeholder: merchant_name_example_helper(@trym_category_id), url: merchants_path(trym_category_id: @trym_category_id), init: {text: "#{@charge.merchant_name}", id: "#{@charge.merchant.present? ? @charge.merchant.id : nil}" }.to_json }}

        .form-inputs
          = f.input :amount, as: :currency, label: "How much is your average bill?", input_html: { value: @charge.amount_in_currency, style: "text-align: center; text-indent: -30px;" }

        .form-inputs
          = f.input :billing_day, as: :string, label: "When is your next charge?", placeholder: "estimate if you're not sure", input_html: {class: "text-center"}
          = f.input :renewal_period_in_weeks, label: "How often are you charged?"

      .modal-footer{ style: "text-align: center;" }
        = render partial: 'shared/cancel_button', locals: {btn_size: 'btn-md'}
        = link_to "delete", {controller: "charges", action: "destroy", id: @charge.id}, method: :delete, class: "btn btn-danger btn-md", style: "width: 69px;", data: {confirm: "Are you sure you want to delete this charge? Deleting a charge also deletes all associated account management requests. This can't be undone."}, remote: true
        = f.button :submit, "Save", class: "btn btn-primary btn-md", style: "width: 69px;"

app/views/charges/_linked_account_list.html.haml
.heading
  %h5
    %i.fa.fa-credit-card
    Linked Accounts
    .pull-right.visible-lg-inline-block
      =link_to linked_accounts_path, class: "btn btn-xs btn-default" do
        %i.fa.fa-plus-circle
        Link New Account
=link_to linked_accounts_path, class: "btn btn-xs btn-block sub-heading-link hidden-lg" do
  %i.fa.fa-plus-circle
  Link new account
.body
  -if current_user.linked_accounts.linked.present?
    -current_user.linked_accounts.linked.each do |fin|
      .item.row
        .col-sm-7.item-label{style: "padding-right:0px"}
          %span=fin.name
        .col-sm-5.col-sm-5.item-stats
          %small
            =link_to linked_account_path(fin) do
              View Account
            %ul.list-inline
              %li{data: {toggle: "tooltip", placement: "top", title: "total transactions"}}
                #{fin.charges.count}
                %i.fa.fa-credit-card
              %li{data: {toggle: "tooltip", placement: "top", title: "recurring expenses"}}
                #{fin.charges.recurring.count}
                %i.fa.fa-refresh
  -else
    .item.row
      .col-sm-12
        %h5
          No Accounts Linked
        %p.small
          =link_to "Link your financial accounts", linked_accounts_path 
          to automatically identify recurring expenses.

app/views/charges/_new.html.haml
.modal-dialog.modal-sm
  .modal-content
    = simple_form_for @charge, remote: request.format.js? do |f|
      .modal-body.text-center
        %h3.modal-title 
          %i.fa.fa-plus-circle
          add a charge
        %p.form-errors
          = f.error_notification
        .form-inputs
          = f.input :recurring_score, as: :hidden, input_html: {value: 10, class: "text-center"}
          = f.input :recurring, as: :hidden, input_html: {value: true, class: "text-center"}
          = f.input :merchant_id, as: :string, label: "Which company is the charge from?", input_html: {class: "text-center", data: {placeholder: merchant_name_example_helper(@trym_category_id), url: merchants_path(trym_category_id: @trym_category_id)}}
          
        .form-inputs
          = f.input :amount, as: :currency, label: "How much is your average bill?", input_html: { style: "text-align: center; text-indent: -30px;" }

        .form-inputs
          = f.input :billing_day, as: :string, label: "When is your next charge?", placeholder: "estimate if you're not sure", input_html: {class: "text-center"}
          = f.input :renewal_period_in_weeks, label: "How often are you charged?", input_html: {class: "text-center"}

      .modal-footer
        .pull-left
          = render partial: 'shared/cancel_button', locals: {btn_size: 'btn-md'}
        .pull-right
          = f.button :submit, "Save", class: "btn btn-primary btn-md"

app/views/charges/_no_charges_content.html.haml
#no-charge-options-container
  .paragraph-spacer
  .trym-fade-in
    .row.text-center
      .col-sm-12
        .trym-talking
          %p.lead.without-margin
            Hi there, let's get started.
      %p.lead
        Add some recurring expenses for me to track.

    .paragraph-spacer

    .row
      .col-sm-10.col-sm-offset-1.text-center
        %p.lead.without-margin
          =link_to linked_accounts_path, class: "btn btn-lg btn-block btn-primary-o btn-icon-left" do
            %span
              %i.fa.fa-credit-card.fa-3x.pull-left
            %span Link me to one or more of your financial accounts and i'll automatically identify your recurring expenses.

    .paragraph-spacer
    %p.lead.text-center.gray
      or if you don't want to link your accounts

    .row
      .col-sm-10.col-sm-offset-1.text-center
        %p.lead.without-margin
          =link_to new_charge_path, class: "btn btn-lg btn-block btn-primary-o btn-icon-left" do
            %span
              %i.fa.fa-plus-circle.fa-3x.pull-left
            %span I can help you quickly organize and input your recurring expenses manually.

    .paragraph-spacer
    %p.lead.text-center.gray
      or if you have a service you want to change right now

    .row
      .col-sm-10.col-sm-offset-1.text-center
        %p.lead.without-margin
          =link_to new_stop_order_path, class: "btn btn-lg btn-block btn-primary-o btn-icon-left" do
            %span
              %i.fa.fa-cogs.fa-3x.pull-left
            %span Cancel, upgrade, or downgrade any service with a few clicks.

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Charges</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th>Amount</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Renewal period in weeks</th>
      <th>Billing day</th>
      <th>Wizard complete</th>
      <th>Last date billed</th>
      <th>Merchant</th>
      <th>Recurring</th>
      <th>Billed to date</th>
      <th>Recurring score</th>
      <th>Transaction request</th>
      <th>Linked account</th>
      <th>Trym category</th>
      <th>History</th>
      <th>Plaid name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= charge.description %></td>
        <td><%= charge.user %></td>
        <td><%= charge.amount %></td>
        <td><%= charge.start_date %></td>
        <td><%= charge.end_date %></td>
        <td><%= charge.renewal_period_in_weeks %></td>
        <td><%= charge.billing_day %></td>
        <td><%= charge.wizard_complete %></td>
        <td><%= charge.last_date_billed %></td>
        <td><%= charge.merchant %></td>
        <td><%= charge.recurring %></td>
        <td><%= charge.billed_to_date %></td>
        <td><%= charge.recurring_score %></td>
        <td><%= charge.transaction_request %></td>
        <td><%= charge.linked_account %></td>
        <td><%= charge.trym_category %></td>
        <td><%= charge.history %></td>
        <td><%= charge.plaid_name %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/index.html.haml
.row
  .col-md-3.col-sm-4.hidden-xs{style: "padding: 0px"}
    #side-list.scroll-pane.scrollable
      = render 'linked_account_list'
      = render 'contact'
      = render 'account_activity'
      = render 'shared/security_and_terms'
  .col-md-9.col-sm-8.scrollable
    -if @charges.present?
      =render 'content'
    -else
      =render 'no_charges_content'
    .paragraph-spacer

app/views/charges/new.html.erb
<h1>New Charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/new.html.haml
.paragraph-spacer

.row.text-center
  .col-sm-10.col-sm-offset-1.col-xs-12
    .trym-talking
      %p.lead.without-margin
        these are the most common categories of recurring expense
    %p.lead click on a category to quickly add an expense in it
    .row
      .col-md-10.col-md-offset-1
        .trym-category-grid
          -TrymCategory.other_last.each do |c|
            -charges = c.charges.where(user_id: current_user.id).recurring
            =link_to new_charge_path(trym_category_id: c.id), class: "trym-category-grid-cell #{charges.present? ? nil : "off"}", remote: true do
              %p.grid-title
                =c.name
              .row
                / TODO: correct calculation of monthly cost
                / .col-xs-6.text-center
                /   -if charges.sum(:amount) > 0
                /     %small
                /       #{number_to_currency charges.sum(:amount) * 100} / month
                .col-xs-12.text-center
                  %small #{charges.count} expenses
    %h5
      =link_to "click here when done adding expenses", charges_path